package IHM;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;

import javax.swing.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

import Utility.BibalExceptions;
import domaine.authentification;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

public class Authentification extends javax.swing.JFrame {

    public Authentification() {
    	setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/bibliotheque_icone.png")));
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        // Change background color of the JFrame to white
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LoginText = new javax.swing.JTextField();
        PasseText = new javax.swing.JPasswordField();
        Connecter = new javax.swing.JButton();
        bibliothequeLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        
        jLabel1.setFont(new Font("High Tower Text", Font.BOLD | Font.ITALIC, 16)); // NOI18N
        jLabel1.setForeground(Color.DARK_GRAY);
        jLabel1.setText("nom d'utilisateur");

        jLabel2.setFont(new Font("High Tower Text", Font.BOLD | Font.ITALIC, 16)); // NOI18N
        jLabel2.setForeground(Color.DARK_GRAY);
        jLabel2.setText("mot de passe");


        Connecter.setText("se connecter");
        Connecter.setFont(new Font("High Tower Text", Font.BOLD | Font.ITALIC, 15)); // NOI18N
        Connecter.setForeground(Color.DARK_GRAY);
        Connecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	
					try {
						ConnecterActionPerformed(evt);
					} catch (Exception e) {
						e.printStackTrace();
					}
				
            }
        });

        bibliothequeLabel.setBackground(java.awt.SystemColor.activeCaption);
        bibliothequeLabel.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        bibliothequeLabel.setForeground(Color.DARK_GRAY);
        bibliothequeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bibliothequeLabel.setText("Gestion de bibliotheque");
        bibliothequeLabel.setBorder(javax.swing.BorderFactory.createLineBorder(Color.DARK_GRAY, 4));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bibl.jpg")));
        
        JButton signin = new JButton();
        signin.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		authentification f = new authentification();
        		
    			try {
					if (f.insert(LoginText.getText(), PasseText.getText())) {
						JOptionPane.showMessageDialog(null, "vous avez cree un compte");
						
					}
				
				} catch (Exception e1) {
					JOptionPane.showMessageDialog(null, "echec");
					e1.printStackTrace();
				
				}
        	}
        });
        signin.setText("sign in ");
        signin.setForeground(Color.DARK_GRAY);
        signin.setFont(new Font("High Tower Text", Font.BOLD | Font.ITALIC, 16));


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        					.addGroup(layout.createSequentialGroup()
        						.addGroup(layout.createParallelGroup(Alignment.LEADING)
        							.addComponent(jLabel1)
        							.addComponent(jLabel2))
        						.addGap(98)
        						.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        							.addComponent(PasseText, Alignment.LEADING)
        							.addComponent(LoginText, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 166, GroupLayout.PREFERRED_SIZE)))
        					.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 521, GroupLayout.PREFERRED_SIZE)
        					.addComponent(bibliothequeLabel, GroupLayout.PREFERRED_SIZE, 478, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(138)
        					.addComponent(Connecter, GroupLayout.PREFERRED_SIZE, 126, GroupLayout.PREFERRED_SIZE)
        					.addGap(50)
        					.addComponent(signin, GroupLayout.PREFERRED_SIZE, 126, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(685, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addComponent(bibliothequeLabel, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(LoginText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel1))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(PasseText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel2))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(Connecter)
        				.addComponent(signin, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 242, GroupLayout.PREFERRED_SIZE)
        			.addGap(181))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold> 

    private void ConnecterActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_ConnecterActionPerformed
        authentification f = new authentification();
    	if(f.check(LoginText.getText(), PasseText.getText())) {
    		Menu m = new Menu();
    		this.dispose();
    		m.setVisible(true);	
        }
    	else {
    		JOptionPane.showMessageDialog(null, "nom ou mot de passe incorrect");
    	}
    }//GEN-LAST:event_ConnecterActionPerformed
    private void signinActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_ConnecterActionPerformed
    	
	}
    //GEN-LAST:event_ConnecterActionPerformed


    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authentification().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Connecter;
    private javax.swing.JTextField LoginText;
    private javax.swing.JPasswordField PasseText;
    private javax.swing.JLabel bibliothequeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
}
