package IHM;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import javax.swing.UIManager;
import java.awt.Color;
/**
 * 
 * @author Diallo & Janati
 */
public class Menu extends javax.swing.JFrame {

    public Menu() {

        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        setResizable(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/bibliotheque_icone.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Deconnecter = new javax.swing.JButton();
        GestionReservationsEmprunts = new javax.swing.JButton();
        GestionUsager = new javax.swing.JButton();
        GestionOeuvresExamplaires = new javax.swing.JButton();
        bibliothequeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setMinimumSize(new java.awt.Dimension(410, 410));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Deconnecter.setFont(new Font("High Tower Text", Font.BOLD | Font.ITALIC, 18)); // NOI18N
        Deconnecter.setForeground(Color.DARK_GRAY);
        Deconnecter.setText("Déconnecter");
        Deconnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeconnecterActionPerformed(evt);
            }
        });

        GestionReservationsEmprunts.setFont(new Font("High Tower Text", Font.BOLD | Font.ITALIC, 18)); // NOI18N
        GestionReservationsEmprunts.setForeground(Color.DARK_GRAY);
        GestionReservationsEmprunts.setText("Gestion Reservations et Emprunts");
        GestionReservationsEmprunts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionReservationsEmpruntsActionPerformed(evt);
            }
        });

        GestionUsager.setFont(new Font("High Tower Text", Font.BOLD | Font.ITALIC, 18)); // NOI18N
        GestionUsager.setForeground(Color.DARK_GRAY);
        GestionUsager.setText("Gestion Des Usagers");
        GestionUsager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionUsagerActionPerformed(evt);
            }
        });

        GestionOeuvresExamplaires.setFont(new Font("High Tower Text", Font.BOLD | Font.ITALIC, 18)); // NOI18N
        GestionOeuvresExamplaires.setForeground(Color.DARK_GRAY);
        GestionOeuvresExamplaires.setText("Gestion Oeuvres et Examplaires");
        GestionOeuvresExamplaires.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionOeuvresExamplairesActionPerformed(evt);
            }
        });

        bibliothequeLabel.setFont(new Font("High Tower Text", Font.BOLD | Font.ITALIC, 30)); // NOI18N
        bibliothequeLabel.setForeground(UIManager.getColor("CheckBox.darkShadow"));
        bibliothequeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bibliothequeLabel.setText("Gestion Bibliothèque");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(87)
        			.addComponent(bibliothequeLabel))
        		.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        			.addGroup(jPanel1Layout.createSequentialGroup()
        				.addContainerGap()
        				.addComponent(Deconnecter, GroupLayout.PREFERRED_SIZE, 309, GroupLayout.PREFERRED_SIZE))
        			.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        				.addGap(137)
        				.addComponent(GestionOeuvresExamplaires, GroupLayout.PREFERRED_SIZE, 313, GroupLayout.PREFERRED_SIZE)))
        		.addComponent(GestionReservationsEmprunts)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(GestionUsager, GroupLayout.PREFERRED_SIZE, 296, GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(bibliothequeLabel, GroupLayout.PREFERRED_SIZE, 143, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(GestionUsager, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
        			.addGap(11)
        			.addComponent(GestionOeuvresExamplaires, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(GestionReservationsEmprunts, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(Deconnecter, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GestionUsagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionUsagerActionPerformed
        GestionUsager gu = new GestionUsager();
        this.dispose();
        gu.setVisible(true);
    }//GEN-LAST:event_GestionUsagerActionPerformed

    private void DeconnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeconnecterActionPerformed
        Authentification a = new Authentification();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_DeconnecterActionPerformed

    private void GestionOeuvresExamplairesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionOeuvresExamplairesActionPerformed
        GestionOeuvresExemplaires goe = new GestionOeuvresExemplaires();
        this.dispose();
        goe.setVisible(true);
    }//GEN-LAST:event_GestionOeuvresExamplairesActionPerformed

    private void GestionReservationsEmpruntsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionReservationsEmpruntsActionPerformed
        GestionReservationsEmprunts gre = new GestionReservationsEmprunts();
        this.dispose();
        gre.setVisible(true);
    }//GEN-LAST:event_GestionReservationsEmpruntsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deconnecter;
    private javax.swing.JButton GestionOeuvresExamplaires;
    private javax.swing.JButton GestionReservationsEmprunts;
    private javax.swing.JButton GestionUsager;
    private javax.swing.JLabel bibliothequeLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
